# Generated by Django 5.1.5 on 2025-01-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_datenow_remove_task_donde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tasks_archivos/', verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='task',
            name='extra',
            field=models.CharField(default=0, max_length=200, verbose_name='Extras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_portadas/'),
        ),
    ]
