# Generated by Django 5.1.5 on 2025-01-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_archivo_task_extra_task_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra',
            field=models.CharField(max_length=200, null=True, verbose_name='Extras'),
        ),
    ]
